name: flexidate
version: 0.8.0+3
homepage: https://github.com/ericmartineau/flexidate
description: A flexible date parsing and handling library
publish_to: 'none'
environment:
  sdk: '>=2.14.0 <3.0.0'
dependencies:
  collection: ^1.15.0
  dartx: ^0.7.1
  # Referencing specific checkin of dartxx required to upgrade other packages (creator didn't publish this update).
  dartxx: 
    git:
      url: https://github.com/ericmartineau/dartxx
      ref: dbd3c9bc1b01253b6da28c029a28e439e4363bef
  equatable: ^2.0.3
  inflection3: ^0.5.3+2
  intl: ^0.18.0
  logging: ^1.0.2
  timezone: ^0.9.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.1
